// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package mallcmd

import (
	"github.com/3lur/go-mall/internal/server"
)

// Injectors from wire.go:

func NewApp() (*server.Server, func(), error) {
	engine := server.NewServerHTTP()
	serverServer := server.NewServer(engine)
	return serverServer, func() {
	}, nil
}
