// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/3lur/go-mall/internal/common/data"
	"github.com/3lur/go-mall/internal/controller"
	"github.com/3lur/go-mall/internal/server"
	"github.com/3lur/go-mall/pkg/config"
)

// Injectors from wire.go:

func NewApp(conf *config.Config) (*server.Server, func(), error) {
	dataData, cleanup, err := data.NewData(conf)
	if err != nil {
		return nil, nil, err
	}
	userController := controller.NewUserController(dataData)
	pingController := controller.NewPingController()
	engine := server.NewServerHTTP(userController, pingController)
	serverServer := server.NewServer(engine)
	return serverServer, func() {
		cleanup()
	}, nil
}
