// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/3lur/go-mall/internal/common/data"
	"github.com/3lur/go-mall/internal/controller"
	"github.com/3lur/go-mall/internal/repo"
	"github.com/3lur/go-mall/internal/server"
	"github.com/3lur/go-mall/internal/service"
	"github.com/3lur/go-mall/pkg/config"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewApp(conf *config.Config) (*server.Server, func(), error) {
	dataData, cleanup, err := data.NewData(conf)
	if err != nil {
		return nil, nil, err
	}
	userRepo := repo.NewUserRepo(dataData)
	userService := service.NewUserService(userRepo)
	userController := controller.NewUserController(userService)
	pingController := controller.NewPingController()
	engine := server.NewServerHTTP(userController, pingController)
	serverServer := server.NewServer(engine)
	return serverServer, func() {
		cleanup()
	}, nil
}

// wire.go:

var controllerSet = wire.NewSet(controller.NewUserController, controller.NewPingController)

var serviceSet = wire.NewSet(service.NewUserService)

var repoSet = wire.NewSet(repo.NewUserRepo)
